<?php

namespace Portal\AdminBundle\Repository;

use Portal\AdminBundle\Entity\Instance;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInstanceDataByIds(array $instanceIds)
    {
        var_dump($instanceIds);
        if (empty($instanceIds)) {
            return [];
        }
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT id, title'
            . ' FROM instance'
            . ' WHERE id IN (' . implode(',', $instanceIds) . ')'
        ;
        $stmt = $dc->prepare($sql);
        $stmt->execute();

        return $stmt->fetchAll() ?: [];
    }

    public function getInstanceList()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT i.title, i.code'
            . ' FROM instance AS i'
//            . ' WHERE code NOT IN (\'' . Instance::MAIN_SITE_INSTANCE_CODE . '\')'
            . ' ORDER BY i.id ASC'
        ;

        return $dc->fetchAll($sql) ?: false;
    }

    public function getInstanceCodeList()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT i.code'
            . ' FROM instance AS i'
            . ' ORDER BY i.id ASC'
        ;

        return $dc->executeQuery($sql)->fetchAll(\PDO::FETCH_COLUMN) ?: [];
    }
}
