<?php

namespace Portal\ContentBundle\Repository;

/**
 * SubscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleSubscribeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroupedEmails()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT email, uid, string_agg(instance_id::text, \',\') AS instances'
            . ' FROM article_subscribe'
            . ' GROUP BY email, uid'
        ;

        return $dc->fetchAll($sql) ?: [];
    }
}
