<?php

namespace Portal\ContentBundle\Repository;


/**
 * ArticleCategoryIconAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoryIconAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
