<?php

namespace Portal\ContentBundle\Repository;


/**
 * ArticleAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
