<?php

namespace Portal\ContentBundle\Repository;

/**
 * ArticleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
