<?php

namespace Portal\ContentBundle\Repository;

/**
 * ContactTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
