<?php

namespace Portal\ContentBundle\Repository;

/**
 * DocumentTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTagRepository extends \Doctrine\ORM\EntityRepository
{
}
