<?php

namespace Portal\ContentBundle\Repository;

/**
 * DocumentAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAttachmentListByDocumentId($id)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT original_file_name, file_type, preview_file_url, preview
                FROM attachment AS a
                WHERE a.id IN (
                    SELECT id
                    FROM document_attachment
                    WHERE document_id = ' . (int)$id . '
                )'
        ;

        return $dc->fetchAll($sql);
    }
}
