<?php

namespace Portal\ContentBundle\Repository;

/**
 * DocumentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllDocumentCategory()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT dc.id, dc.slug, dc.title
                FROM document_category AS dc
                ORDER BY dc.id ASC'
        ;

        return $dc->fetchAll($sql) ?: [];
    }
}
