<?php

namespace Portal\ContentBundle\Repository;

/**
 * EventAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
