<?php

namespace Portal\ContentBundle\Repository;

use Portal\ContentBundle\Entity\FeedbackCategory;

/**
 * FeedbackCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllFeedbackCategoryForPagination()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql =
            ' SELECT fc.id as feedback_category_id '
            . ', fc.label as feedback_category_label '
            . ' FROM feedback_category AS fc '
            . ' WHERE code_group = ' . $dc->quote(FeedbackCategory::DEFAULT_GROUP, \PDO::PARAM_STR)
            . ' ORDER BY fc.label ASC ';
        $result = $dc->executeQuery($sql)->fetchAll();

        return $result ?: [];
    }
}
