<?php

namespace Portal\ContentBundle\Repository;

/**
 * FeedbackFormValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackFormValueRepository extends \Doctrine\ORM\EntityRepository
{
}
