<?php

namespace Portal\ContentBundle\Repository;

/**
 * FeedbackFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackFormRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllFeedbackFormForPagination()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT
                    f.id as feedback_form_id,
                    f.title as feedback_form_title,
                    f.email_responsible as feedback_form_email_responsible,
                    f.author_id
                FROM feedback_form AS f 
                ORDER BY f.title ASC';

        return $dc->fetchAll($sql) ?: [];
    }

    public function getFeedbackForm()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql =
            " SELECT * "
            . " FROM feedback_form AS f "
            . " ORDER BY f.id DESC "
            . " LIMIT 1 "
        ;
        $result = $dc->executeQuery($sql)->fetch();

        return $result ?: false;
    }
}
