<?php

namespace Portal\ContentBundle\Repository;

/**
 * FeedbackFieldSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackFieldSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
