<?php

namespace Portal\ContentBundle\Repository;


/**
 * HeadAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
