<?php

namespace Portal\ContentBundle\Repository;

/**
 * instanceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoryListWithArticle()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT
                    ic.title AS instance_category_title,
                    a.category_id AS instance_category_id,
                    count(a.id) AS article_count
                FROM article AS a
                    INNER JOIN instance_category AS ic ON ic.id = a.category_id
                WHERE a.is_published IS TRUE
                    AND a.is_deleted IS NOT TRUE
                GROUP BY a.category_id, ic.id
                ORDER BY ic.sort_order ASC'
        ;

        return $dc->fetchAll($sql) ?: false;
    }

    public function getInstanceList()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT i.title, i.code
                FROM instance AS i
                ORDER BY i.id ASC'
        ;

        return $dc->fetchAll($sql) ?: false;
    }
}
