<?php

namespace Portal\ContentBundle\Repository;

/**
 * InternetResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternetResourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
