<?php

namespace Portal\ContentBundle\Repository;

/**
 * InteractiveMapTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractiveMapTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
