<?php

namespace Portal\ContentBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPages()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT p.id as page_id, p.template_id as page_template_id, p.title as page_title, p.author_id
                FROM page AS p
                ORDER BY p.created_at DESC'
        ;

        return $dc->fetchAll($sql) ?: [];
    }
}
