<?php

namespace Portal\ContentBundle\Repository;

/**
 * ParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends \Doctrine\ORM\EntityRepository
{
}
