<?php

namespace Portal\ContentBundle\Repository;

/**
 * PhotoReportAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoReportAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
