<?php

namespace Portal\ContentBundle\Repository;

/**
 * QuizAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
