<?php

namespace Portal\ContentBundle\Repository;

/**
 * QuizQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
