<?php

namespace Portal\ContentBundle\Repository;

/**
 * SiteMapTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteMapTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
