<?php

namespace Portal\ContentBundle\Repository;

/**
 * StandardTemplateAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardTemplateAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
