<?php

namespace Portal\ContentBundle\Repository;

/**
 * StandardTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
