<?php

namespace Portal\ContentBundle\Repository;

/**
 * StructureTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureTemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStructureInterviewsList($structureId, $offset = 0)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT *'
            . ' FROM interview AS i'
            . ' WHERE i.is_published IS true'
            . ' AND i.menu_node_id = ' . (int)$structureId
            . ' AND i.is_deleted IS NOT true '
            . ' ORDER BY i.date_end DESC'
            . ' OFFSET ' . (int)$offset
        ;

        return $dc->fetchAll($sql) ?: false;
    }

    public function getStructureArticlesList($structureId, $offset)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT a.*, aa.article_id, at.preview_file_url AS attachment'
            . ' FROM article AS a'
            . ' LEFT JOIN article_attachment AS aa ON a.id = aa.article_id'
            . ' LEFT JOIN attachment AS at ON aa.id = at.id'
            . ' WHERE a.is_published IS true'
            . ' AND a.menu_node_id = ' . (int)$structureId
            . ' ORDER BY a.created_at DESC'
            . ' OFFSET ' . (int)$offset
        ;

        return $dc->fetchAll($sql) ?: false;
    }

    public function getMaxOrderChildStructure($structureId)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT
            MAX(node_order)
            FROM menu_node AS mn
            WHERE mn.parent_id = ' . $dc->quote($structureId, \PDO::PARAM_INT)
        ;

        return $dc->executeQuery($sql)->fetch(\PDO::FETCH_COLUMN) ?: false;
    }
}
