<?php

namespace Portal\ContentBundle\Repository;

use Portal\ContentBundle\Entity\SystemMode;

/**
 * SystemModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemModeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllSystemMode()
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql =
            " SELECT "
            . " sm.id as system_mode_id "
            . ", sm.code as system_mode_code "
            . " FROM system_mode AS sm "
        ;
        $result = $dc->fetchAll($sql);

        return $result;
    }

    public function getSystemModeByCode($mode)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql =
            " SELECT "
            . " sm.notification_message as system_mode_notification_message "
            . ", sm.mode_message as system_mode_mode_message "
            . ", sm.is_active_notification as system_mode_is_active_notification "
            . ", sm.is_active_mode as system_mode_is_active_mode "
            . " FROM system_mode AS sm "
            . " WHERE sm.code LIKE ". $dc->quote($mode, \PDO::PARAM_STR)
        ;
        $result = $dc->executeQuery($sql)->fetch();

        return $result;

    }
}
