<?php

namespace Portal\ContentBundle\Repository;

/**
 * TableTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
