<?php

namespace Portal\ContentBundle\Repository;

/**
 * TypoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypoRepository extends \Doctrine\ORM\EntityRepository
{
}
