<?php

namespace Portal\ContentBundle\Repository;

/**
 * VideoReportAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoReportAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
