<?php

namespace Portal\ContentBundle\Repository;

/**
 * VisitcardTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitcardTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
