<?php

namespace Portal\ContentBundle\Repository;

/**
 * VisitcardAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitcardAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
