<?php

namespace Portal\ContentBundle\Repository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends \Doctrine\ORM\EntityRepository
{}
