<?php

namespace Portal\ContentBundle\Repository;

/**
 * WidgetPanelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetPanelRepository extends \Doctrine\ORM\EntityRepository
{
}
