<?php

namespace Portal\UserBundle\Entity\Repository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     * @return array
     */
    public function getPermissionsList($params = [])
    {
        $queryBuilder = $this->createQueryBuilder('permissionObj');
        $queryBuilder
            ->add('orderBy', 'permissionObj.label ASC')
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
