<?php

namespace Portal\UserBundle\Entity\Repository;

/**
 * RoleToPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleToPermissionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Remove all permissions
     * @param int $roleId
     * @return mixed
     */
    public function unsetPermissions($roleId)
    {
        $dc = $this->getEntityManager()->getConnection();
        $dc->connect('master');
        $sql = 'DELETE'
            . ' FROM user_role2permission roleToPermissions'
            . ' WHERE roleToPermissions.role_id = ' . (int)$roleId
        ;

        $dc->executeQuery($sql);

        return true;
    }

    public function getPermissionsByRoleId($roleId)
    {
        $dc = $this->getEntityManager()->getConnection();
        $sql = 'SELECT up.id, up.code, up.label'
            . ' FROM user_role2permission AS ur'
            . ' JOIN user_permission AS up ON ur.permission_id = up.id'
            . ' WHERE ur.role_id = ' . (int)$roleId
        ;

        return $dc->fetchAll($sql);
    }
}
