Portal\ContentBundle\Entity\Document:
  file:
    mapping:            document_attachment_mapping
    filename_property:  preview
    size:               fileSize
    mime_type:          fileType
    original_name:      originalFileName