Portal\ContentBundle\Entity\Article:
  file:
    mapping:            article_preview_attachment_mapping
    filename_property:  preview
    size:               fileSize
    mime_type:          fileType
    original_name:      originalFileName